services:
  - type: web
    name: run2mind-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py initialize_data_in_run2mind
      python manage.py shell -c "
from django.contrib.auth import get_user_model;
User = get_user_model();
email = 'admin@admin.com';
password = '123456';
username = 'admin';
if not User.objects.filter(username=username).exists():
    User.objects.create_superuser(username=username, email=email, password=password)"
    startCommand: gunicorn run2mind.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: run2mind.settings
      - key: DATABASE_URL
        fromDatabase:
          name: run2mind-db
          property: connectionString
      - key: SECRET_KEY
        value: h_OS9ipa5I_NkiMjoew4xQIR2bJ_roveaxczI27KQndfbqb7Plf8mpc9VgJz1yt4tqo
      - key: ALLOWED_HOSTS
        value: run2mind-django.onrender.com
      - key: DEBUG
        value: 'False'

databases:
  - name: run2mind-db
    databaseName: run2mind
    user: run2mind_user
    plan: free
    region: oregon

staticPublishPath: staticfiles
