"""
Django settings for run2mind project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os.path
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aqs90*xid(d$!m@2z8jhr$*f&c63t0h)q!#)7s@si!rmqt44c%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'rest_framework',
    'corsheaders',

    'customusers.apps.CustomusersConfig',
    'customgroups.apps.CustomgroupsConfig',
    'customusergroup.apps.CustomusergroupConfig',
    'customgrouppermissions.apps.CustomgrouppermissionsConfig',
    'login.apps.LoginConfig',
    'dashboard.apps.DashboardConfig',
    'experts.apps.ExpertsConfig',
    'expertsessions.apps.ExpertsessionsConfig',
    'patients.apps.PatientsConfig',
    'appointments.apps.AppointmentsConfig',
    'sessionappointments.apps.SessionappointmentsConfig',
    
    'channels',
    'chatnests.apps.ChatnestsConfig',
    'chatbot.apps.ChatbotConfig',
]

AUTH_USER_MODEL = 'customusers.Customusers'
ASGI_APPLICATION = 'chatnests.asgi.application' 

#CHANNEL_LAYERS  settings Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',

]

CORS_ALLOW_ALL_ORIGINS = True  #ابقي اللغيها

ROOT_URLCONF = 'run2mind.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'run2mind.wsgi.application'


# إعدادات الاتصال بـ wait.ai
WIT_AI_API_KEY = 'RGSEANT4KIBWDHU2USDN7ZDNMUD3K5TT'  # تأكد من صحة المفتاح
WAIT_AI_SETTINGS = {
    'API_KEY': WIT_AI_API_KEY,
    'ENDPOINT': 'https://api.wit.ai/',
    'DEFAULT_LANGUAGE': 'ar',
    'DEBUG': True,
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'run2mind_db',
        'USER': 'run2mind_db_user',
        'PASSWORD': 'OoqSoYMQvg0K8a6bqNy5l0U1zaZCJCv7',
        'HOST': 'dpg-d1vt0mer433s7381b9tg-a.oregon-postgres.render.com',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/



LANGUAGE_CODE = 'ar'
LANGUAGES = [
    ("ar", _("Arabic")),
    ("en", _("English")),
]


DEFAULT_CHARSET = 'utf-8'

LOCALE_PATHS = [
   os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_L10N = True

USE_TZ = False



# Social Authentication Backends
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # Google OAuth2
    'django.contrib.auth.backends.ModelBackend', # Django default
)


SOCIAL_AUTH_RAISE_EXCEPTIONS = True  # رفع الأخطاء لمزيد من التفاصيل
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '52490079473-ngvconl4kqs3huadd8tv1acbqm3131r5.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/en/dashboard/list/'  
LOGOUT_REDIRECT_URL = '/'

SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_REDIRECT_URLS = [
    'http://127.0.0.1:8000/en/auth/complete/google-oauth2/',
    'http://127.0.0.1:8000/ar/auth/complete/google-oauth2/',
]

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile', 'openid']

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_user',  
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',

    # دوال مخصصة
    'login.pipeline.custom_social_details',  
    'login.pipeline.custom_social_uid',      
    'login.pipeline.custom_social_user',     
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.user.get_username',
    'login.pipeline.custom_create_user',     
    'social_core.pipeline.social_auth.associate_user',
    'login.pipeline.custom_load_extra_data',
    'login.pipeline.custom_user_details',    
    'login.pipeline.debug_step',             
)







# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/assets/'
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login:login'
