# Generated by Django 5.2.4 on 2025-07-22 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, verbose_name='Gender')),
                ('experience_years', models.PositiveIntegerField(default=25, verbose_name='Years of Experience')),
                ('file', models.FileField(blank=True, null=True, upload_to='experts/')),
                ('specialization_ar', models.CharField(max_length=255, verbose_name='Specialization (Arabic)')),
                ('specialization_en', models.CharField(max_length=255, verbose_name='Specialization (English)')),
                ('certificates_ar', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Certificates (Arabic)')),
                ('certificates_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Certificates (English)')),
                ('details_ar', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Details (Arabic)')),
                ('details_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Details (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Experts',
                'db_table': 'experts',
            },
        ),
    ]
