# Generated by Django 5.2.4 on 2025-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatnests_blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chatnests_chatpermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_from', models.CharField(choices=[('expert', 'Expert'), ('patient', 'Patient')], max_length=20)),
                ('role_to', models.CharField(choices=[('expert', 'Expert'), ('patient', 'Patient')], max_length=20)),
                ('can_chat', models.BooleanField(default=True)),
                ('message_types_allowed', models.JSONField(default=list, help_text="List of allowed message types for this role pair (e.g., ['text', 'image']).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'chatnests_chatpermission',
            },
        ),
        migrations.CreateModel(
            name='Chatnests_chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=10)),
                ('room_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'chatnests_chatroom',
            },
        ),
        migrations.CreateModel(
            name='Chatnests_chatroom_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'chatnests_chatroom_participants',
            },
        ),
        migrations.CreateModel(
            name='Chatnests_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='text', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'chatnests_message',
            },
        ),
    ]
