# Generated by Django 5.2.4 on 2025-07-22 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availabletimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
            ],
            options={
                'verbose_name': 'Availabletime',
                'verbose_name_plural': 'Availabletimes',
                'db_table': 'availabletimes',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('arabic', 'Arabic'), ('english', 'English')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Sessiondurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes')], help_text='Duration in minutes')),
            ],
            options={
                'verbose_name': 'Sessionduration',
                'verbose_name_plural': 'Sessiondurations',
                'db_table': 'sessiondurations',
            },
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Timeslot',
                'verbose_name_plural': 'Timeslots',
                'db_table': 'timeslots',
            },
        ),
        migrations.CreateModel(
            name='Expertsessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_price', models.DecimalField(decimal_places=0, default=800, max_digits=6)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('availabletimes', models.ManyToManyField(related_name='Availabletimes', to='expertsessions.availabletimes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expertsessions_created', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_session', to='experts.experts')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expertsessions_updated', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(related_name='expertsessions', to='expertsessions.languages')),
                ('sessionduration', models.ManyToManyField(related_name='Sessiondurations', to='expertsessions.sessiondurations')),
            ],
            options={
                'verbose_name': 'Expertsession',
                'verbose_name_plural': 'Expertsessions',
                'db_table': 'expertsessions',
            },
        ),
        migrations.AddField(
            model_name='availabletimes',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertsessions.timeslots'),
        ),
    ]
